@echo off
echo Starting Dwelo servers...

echo Starting backend server...
start "Dwelo Server" cmd /k "cd server && npm start"

echo Starting frontend client...
start "Dwelo Client" cmd /k "cd client && npm run dev"

echo Both servers are starting...
echo Backend will be available at: http://localhost:5001
echo Frontend will be available at: http://localhost:5173
echo.
echo Press any key to close this window...
pause > nul 